const pieceUI = [
    { displayName: "Alpha", displayCode: "alpha" },
    { displayName: "Anarcandy", displayCode: "anarcandy" },
    { displayName: "Caliente", displayCode: "caliente" },
    { displayName: "California", displayCode: "california" },
    { displayName: "Cardinal", displayCode: "cardinal" },
    { displayName: "Cburnett", displayCode: "cburnett" },
    { displayName: "Celtic", displayCode: "celtic" },
    { displayName: "Chess 7", displayCode: "chess7" },
    { displayName: "Chessnut", displayCode: "chessnut" },
    { displayName: "Companion", displayCode: "companion" },
    { displayName: "Cooke", displayCode: "cooke" },
    // { displayName: "Disguised", displayCode: "disguised" },
    // { displayName: "Dubronovny", displayCode: "dubronovny" },
    { displayName: "Fantasy", displayCode: "fantasy" },
    { displayName: "Fresca", displayCode: "fresca" },
    { displayName: "Gioco", displayCode: "gioco" },
    { displayName: "Governor", displayCode: "governor" },
    { displayName: "Horsey", displayCode: "horsey" },
    { displayName: "Ic Pieces", displayCode: "icpieces" },
    // { displayName: "Kiwensuwi", displayCode: "kiwenSuwi" },
    { displayName: "Kosal", displayCode: "kosal" },
    { displayName: "Leipzig", displayCode: "leipzig" },
    { displayName: "Letter", displayCode: "letter" },
    { displayName: "Maestro", displayCode: "maestro" },
    { displayName: "Merida", displayCode: "merida" },
    { displayName: "Monarchy", displayCode: "monarchy" },
    // { displayName: "Mono", displayCode: "mono" },
    { displayName: "Mpchess", displayCode: "mpchess" },
    { displayName: "Pirouetti", displayCode: "pirouetti" },
    { displayName: "Pixel", displayCode: "pixel" },
    { displayName: "Reillycraig", displayCode: "reillycraig" },
    { displayName: "Riohacha", displayCode: "riohacha" },
    { displayName: "Shapes", displayCode: "shapes" },
    { displayName: "Spatial", displayCode: "spatial" },
    { displayName: "Staunty", displayCode: "staunty" },
    { displayName: "Tatiana", displayCode: "tatiana" }
  ];

  export default pieceUI;